import { cn } from "@/libs/utils";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import { Toaster } from "@/components/ui/Toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html
            lang="en"
            className={
                (cn("bg-white text-slate-900 antialiased "), inter.className)
            }
        >
            <body className="h-screen bg-slate-50 antialiased pt-20 flex flex-col">
                {children}

                <Toaster position="bottom-right" />

                <Navbar />

                {/* Allow for more height in mobile devices */}
                <div className="h-40 md:hidden" />
            </body>
        </html>
    );
}
