import { cn } from "@/lib/utils";
import "./globals.css";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/Toast";
import { Metadata } from "next";
import Head from "next/head";
import Link from "next/link";
import Icons from "@/components/Icons";
import { getAuthSession } from "@/lib/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Tost | The best",
    description: "Generated by create next app",
    icons: {
        icon: {
            url: "/favicon.png",
        },
    },
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const session = await getAuthSession();

    return (
        <html
            lang="en"
            className={
                (cn("bg-white text-slate-900 antialiased "), inter.className)
            }
        >
            <Head>
                <link rel="shortcut icon" href="/favicon.ico" />
            </Head>

            <body className="h-screen bg-slate-50 antialiased flex flex-col">
                {children}

                <Toaster position="bottom-right" />

                {/* Allow for more height in mobile devices */}
                <div className="h-40 md:hidden" />

                {session?.user.role === "ADMIN" ? (
                    <div className="fixed bottom-10 right-10">
                        <Link
                            href="/admin/users"
                            className="flex justify-center items-center h-14 w-14 bg-custom-red hover:bg-custom-red-hov text-white rounded-full"
                        >
                            <Icons.UserCog />
                        </Link>
                    </div>
                ) : null}
            </body>
        </html>
    );
}
